"""
SepraAI v2.7 — Pydantic Schemas & Validation Contracts

Enforces strict boundaries on input parsing, execution metadata, and checkpoints.
Satisfies the Schema Rule (Patch #4) by rejecting arbitrary fields and dynamic parameters.
"""

from __future__ import annotations

import re
import uuid
from typing import Any
from pydantic import BaseModel, Field, field_validator, ConfigDict

from core.models import JobStatus, ChunkStatus, RendererType, WorkerPool, DLQReason

# Whitelist pattern: only alphanumeric, dashes, underscores, and forward slashes allowed.
# Strictly blocks parent directory traversal ('..') or system directories.
PATH_WHITELIST_REGEX = re.compile(r"^(?!\.\.)[a-zA-Z0-9_\-\/\.]+$")


class PathValidatorMixin:
    """Helper validator class for path fields."""

    @classmethod
    def validate_filepath(cls, v: str | None) -> str | None:
        if v is None:
            return v
        # Ensure it conforms to the strict characters whitelist and has no traversal sequences
        if ".." in v or "/" not in v and v.startswith("."):
            raise ValueError(f"Path traversal sequence detected in file path: {v}")
        if not PATH_WHITELIST_REGEX.match(v):
            raise ValueError(
                f"File path contains invalid characters or formats. "
                f"Path must match whitelist: {v}"
            )
        return v


# ── Scene Checkpoint Schema (Strict validation, Patch #4) ──────────────────

class SceneCheckpointSchema(BaseModel):
    """
    Stateless snapshot schema containing visual elements.
    Enforces Strict validation and forbids extra/unmapped parameters (Patch #4).
    """
    model_config = ConfigDict(
        extra="forbid",
        strict=True,
    )

    chunk_id: uuid.UUID
    renderer_type: RendererType
    objects_data: dict[str, Any]

    @field_validator("objects_data")
    @classmethod
    def validate_objects_recursive(cls, v: dict[str, Any]) -> dict[str, Any]:
        """
        Deep-checks objects_data structures to catch dynamic evaluation keys (like src, eval)
        that could be steerable or lead to code injection on deserialization.
        """
        # Block potential dynamic injection attributes
        blacklist_keys = {"eval", "exec", "require", "import", "system", "subprocess", "spawn"}

        def scan_dict(d: dict[str, Any]) -> None:
            for key, val in d.items():
                if key.lower() in blacklist_keys:
                    raise ValueError(f"SecurityViolation: Blocked reserved key '{key}' in objects_data.")
                if isinstance(val, dict):
                    scan_dict(val)
                elif isinstance(val, list):
                    scan_list(val)
                elif isinstance(val, str):
                    # Check string values for directory traversal or malicious injection sequences
                    if ".." in val or "/etc/" in val:
                        raise ValueError(f"SecurityViolation: Traversal detected in object attribute: {val}")

        def scan_list(lst: list[Any]) -> None:
            for item in lst:
                if isinstance(item, dict):
                    scan_dict(item)
                elif isinstance(item, list):
                    scan_list(item)

        scan_dict(v)
        return v


# ── Internal Worker Schemas ───────────────────────────────────────────────

class ChunkRenderResult(BaseModel, PathValidatorMixin):
    """
    Schema returned by render workers on success.
    Enforces deterministic properties and paths.
    """
    model_config = ConfigDict(strict=True)

    chunk_id: uuid.UUID
    content_hash: str = Field(..., min_length=64, max_length=64)
    video_path: str
    audio_path: str

    @field_validator("video_path", "audio_path")
    @classmethod
    def check_paths(cls, v: str) -> str:
        res = cls.validate_filepath(v)
        if not res:
            raise ValueError("Path validation returned empty result")
        return res


# ── Healing & Agent Schemas (Patch #11) ───────────────────────────────────

class HealingRequest(BaseModel):
    """
    Schema passed to the Healing Agent.
    Supports escalating retry metrics.
    """
    model_config = ConfigDict(strict=True)

    chunk_id: uuid.UUID
    attempt_number: int = Field(..., ge=1, le=10)
    temperature: float = Field(..., ge=0.0, le=1.0)
    prior_error_context: str
    original_code: str
    layout_override_triggered: bool = False


class ConsensusVerdict(BaseModel):
    """
    Unified evaluation output generated by the Consensus Node (Patch #10).
    """
    model_config = ConfigDict(strict=True)

    passed: bool
    professor_errors: list[str] = Field(default_factory=list)
    art_director_errors: list[str] = Field(default_factory=list)
    resolved_fix_instructions: str | None = None
    contradiction_detected: bool = False
    force_layout_override: bool = False


# ── Job Request & Response Schemas ────────────────────────────────────────

class CurriculumJobCreate(BaseModel):
    original_prompt: str = Field(..., min_length=5)


class CurriculumJobResponse(BaseModel):
    id: uuid.UUID
    status: JobStatus
    created_at: Any


class VideoPartJobResponse(BaseModel):
    id: uuid.UUID
    curriculum_job_id: uuid.UUID
    part_number: int
    status: JobStatus
    approved_by: str | None
    created_at: Any


class CurriculumJobDetailResponse(BaseModel):
    id: uuid.UUID
    status: JobStatus
    original_prompt: str
    video_parts: list[VideoPartJobResponse] = []
    created_at: Any


# ── Chemistry Video Service Schemas ───────────────────────────────────────

class ChemistryVideoJobCreate(BaseModel):
    concept: str = Field(..., min_length=3)


class ChemistryVideoJobResponse(BaseModel):
    id: uuid.UUID
    concept: str
    status: str
    video_path: str | None = None
    error_message: str | None = None
    retry_count: int
    created_at: Any
    updated_at: Any


# ── Quiz Service Schemas ──────────────────────────────────────────────────

class QuizJobCreate(BaseModel):
    subject: str = Field(..., min_length=3)
    difficulty: str = Field(..., description="Difficulty level, e.g. Beginner, Intermediate, Advanced")
    num_items: int = Field(..., ge=1, le=20)


class QuizItemResponse(BaseModel):
    id: uuid.UUID
    question: str
    choices: list[str]
    correct_answer: str
    explanation: str
    cost_usd: float
    attempts: int


class QuizJobResponse(BaseModel):
    id: uuid.UUID
    subject: str
    difficulty: str
    num_items: int
    status: str
    total_cost: float
    created_at: Any
    updated_at: Any
    items: list[QuizItemResponse] = []
